### ISSUE TITLE
Catches everyone's messages rather than one person.

### ISSUE THREAD

**Issue by Babyhamsta** [Michael-J-Scofield/discord-anti-spam#1]
I thought this was a personal 1 on 1 anti spam.
If it is then it does a really bad job because people can spam and if someone else talks while they are spamming it catches both people or just the person who ended up talking in the middle.
People who aren't even spamming get the warning message for spamming.

**Comment by Michael-J-Scofield** [comment]
Increase warn and maxbuffer.

**Comment by motasim1** [comment]
I increased the warn and max buffer, but it still catches people who sent a message at the same time the spammer sent it
