### ISSUE TITLE
How do i make it delete spammed messages?

### ISSUE THREAD

**Issue by Nya0** [Michael-J-Scofield/discord-anti-spam#100]
How do i make it delete spammed messages? i saw there was an update to toggle that but idk how, and i keep getting this error 
` | DiscordAPIError: Unknown User
0|bot  |     at /root/PB-master/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
0|bot  |     at /root/PB-master/node_modules/snekfetch/src/index.js:215:21
0|bot  |     at runMicrotasks (<anonymous>)
0|bot  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
0|bot  |   path: '/api/v7/guilds/374071874222686211/members/696223811678240809',
0|bot  |   code: 10013,
0|bot  |   method: 'GET'
0|bot  | }`

**Comment by Scraayp** [comment]
It will be aviable in the next update!

**Comment by Scraayp** [comment]
The update isn't merged yes! So it isn't possible for now.

**Comment by Nya0** [comment]
and i keep getting the error DiscordAPIError: Unknown User

**Comment by Scraayp** [comment]
@Nya0 Full error please!

**Comment by Nya0** [comment]
Here!
`0|bot  | DiscordAPIError: Unknown User
0|bot  |     at /root/PB-master/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
0|bot  |     at /root/PB-master/node_modules/snekfetch/src/index.js:215:21
0|bot  |     at runMicrotasks (<anonymous>)
0|bot  |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
0|bot  |   path: '/api/v7/guilds/374071874222686211/members/696223845669011596',
0|bot  |   code: 10013,
0|bot  |   method: 'GET'
0|bot  | }`

**Comment by Scraayp** [comment]
It's not a fault on our side!
