### ISSUE TITLE
Terrible Staff!!!

### ISSUE THREAD

**Issue by akahomie** [Michael-J-Scofield/discord-anti-spam#103]

**Comment by Scraayp** [comment]
Hahahaha.

**Comment by akahomie** [comment]
The staff is terrible and they got into an argument with be because they were acting like an ass. And they kicked me because the have a bad personality!

**Comment by Scraayp** [comment]
Why

**Comment by Scraayp** [comment]
We are not acting like a ass.

**Comment by Michael-J-Scofield** [comment]
This is a product made by a company where you can get 24/7 support. Product comes as is, free of charge and you’re expected to know what you’re doing when you utilize it.

**Comment by Scraayp** [comment]
@akahomie rejoin the server https://discord.gg/XytVyG. And we will discuss with you about it!
Because github isn't a good place for it
