### ISSUE TITLE
All codes are not working

### ISSUE THREAD

**Issue by RPGTheGreat** [Michael-J-Scofield/discord-anti-spam#109]
A-z all codes not working no error

**Comment by Scraayp** [comment]
Can you explain what you mean with codes?

**Comment by umittaylan** [comment]
> A-z all codes not working no error

Same, can you fix it ?

**Comment by Scraayp** [comment]
If you don't descrive what is not working.
How do you want us to fix it?

**Comment by suhd00d** [comment]
Basically none of the antispam measures are working.

**Comment by Scraayp** [comment]
You have probally done something wrong in your code! 

All updates were tested and fixed. So everything should work!
