### ISSUE TITLE
Invalid bitfield flag or number.

### ISSUE THREAD

**Issue by idc-Fab** [Michael-J-Scofield/discord-anti-spam#113]
IDK why this error :/ I did everything perfectly.
![image](https://user-images.githubusercontent.com/68937935/100979109-5fcc6100-3569-11eb-9e68-c820ae6d07e3.png)

**Comment by Scraayp** [comment]
What do you have on the ingnorPermissions option?

**Comment by idc-Fab** [comment]
@Scraayp nothing

**Comment by idc-Fab** [comment]
@Scraayp do u mean exemptPermissions or ignorePermissions?

**Comment by Scraayp** [comment]
Just send all your options

**Comment by idc-Fab** [comment]
@Scraayp ok here => 
![image](https://user-images.githubusercontent.com/68937935/101039082-c3728080-35a1-11eb-889c-82eb855f89b8.png)

**Comment by Scraayp** [comment]
In exemptPermissions it says ADMINSTRATOR but it should be ADMINISTRATOR

**Comment by idc-Fab** [comment]
> In exemptPermissions it says ADMINSTRATOR but it should be ADMINISTRATOR

Oh sorry my bad ;(

**Comment by Scraayp** [comment]
Does it work now?

**Comment by idc-Fab** [comment]
@Scraayp I changed the spelling now there is no error but when I spam there is no warning,

**Comment by Scraayp** [comment]
Have you posted the ```antiSpam.message``` function into your message event

**Comment by idc-Fab** [comment]
@Scraayp yes

**Comment by Scraayp** [comment]
could you please provide me your full index file! Post it to hastebin or any other provider and send a public link to it!

**Comment by idc-Fab** [comment]
@Scraayp wait what? really I need to post my index file??

**Comment by idc-Fab** [comment]
https://hasteb.in/xoyeyovi.php @Scraayp here you go

**Comment by Scraayp** [comment]
You can remove it now. And I have no idea why it doesn't work. Try refreshing the cache and logging everything to get more information!!

**Comment by idc-Fab** [comment]
@Scraayp oh ok :(  Should I close this issue?

**Comment by Scraayp** [comment]
You can, :)
