### ISSUE TITLE
Gives "Could not ban becauae of improper permissions" error in chat even on successful ban.

### ISSUE THREAD

**Issue by tworow2** [Michael-J-Scofield/discord-anti-spam#117]
The bot sends the permission error in chat even though it successfully bans. Seems to occur both with default settings and customized ones.

I've enabled mod logs, and bans are reported correctly there. The ban reason is also correctly entered as "Spamming!" so everything ban related but the message sent to the channel being spammed seems to work.

**Comment by Scraayp** [comment]
I see no reason in the code why it would happen at the moment! 

If the message is really annoying you could mae line 270-279 comment (//) so the message is not sent anymore!

**Comment by Gutzy-hub** [comment]
I have also started to recieve this message and the ban is successful. In the console i am recieving a discordAPIError: Unknown Message.

**Comment by Scraayp** [comment]
Those are 2 different things. 

Non proper perms 
And
Unknown message. 

But i know the problem. Will throw out an pr tommorow about it! (If i dont forget)

**Comment by Gutzy-hub** [comment]
Sounds great thank you
