### ISSUE TITLE
ON/OFF

### ISSUE THREAD

**Issue by Ult1m1** [Michael-J-Scofield/discord-anti-spam#120]
Hi, I have an idea that I would use personally

Exemple:

const AntiSpam = require('discord-anti-spam');
const antiSpam = new AntiSpam({

antispam: true

});

EDIT:
This is not work:

    banEnabled: false,
    warnEnabled: false,
    muteEnabled: false,
    kickEnabled: false,

**Comment by arepp23** [comment]
I am having the same issue. 

`false || true` will always evaluate to true...

**Comment by Scraayp** [comment]
I will try out the find the issue, but there is nothing wrong in the code actually! 

If you could reference any code which you guys are using, so I can debug that!

**Comment by Mathie01** [comment]
When the muteEnabled option is set to false, it still tries to add the muted role to the user.

Error of Discord API with muteEnabled set to false : DiscordAPIError: Missing Permissions

Config : 

`const antiSpam = new AntiSpam({
	warnThreshold: 3, // Amount of messages sent in a row that will cause a warning.
	kickThreshold: 7, // Amount of messages sent in a row that will cause a kick.
	maxInterval: 2000, // Amount of time (in milliseconds) in which messages are considered spam.
	warnMessage: '{@user}, stop spamming.', // Message that will be sent in chat upon warning a user.
	kickMessage: '**{user_tag}** has been kicked for spamming.', // Message that will be sent in chat upon kicking a user.
	maxDuplicatesWarning: 6, // Amount of duplicate messages that trigger a warning.
	maxDuplicatesKick: 10, // Amount of duplicate messages that trigger a warning.
	ignoreBots: true, // Ignore bot messages.
	removeMessages: true, // If the bot should remove all the spam messages when taking action on a user!
    removeBotMessages: true,
    muteEnabled: false,
    banEnnabled: false
});`

**Comment by Scraayp** [comment]
Error of Discord API with muteEnabled set to false : DiscordAPIError: Missing Permissions (Putting Role)

Give the bot permission...

**Comment by Mathie01** [comment]
No, because I have disabled the mute.
I don't want the bot to mute a user, so it is not supposed to give a role

It's just not possible to set muteEnabled to false. There is an error in the code as far as I can see. This is also a problem with banEnabled, warnEnabled, ...

**Comment by Scraayp** [comment]
I will look into it. But most likely it's your own fault!

Just saying

**Comment by Mathie01** [comment]
It seems that the problem has been corrected in the commit https://github.com/Michael-J-Scofield/discord-anti-spam/commit/3bb78e4bc8ecd7d9e8700d05a6940d08eebc9d9a

But installing the package via npm does not retrieve the latest version from the repository : 

```js
warnEnabled: options.warnEnabled || true,
kickEnabled: options.kickEnabled || true,
muteEnabled: options.muteEnabled || true,
banEnabled: options.banEnabled || true,
```

**Comment by Scraayp** [comment]
Yes, that's normal. It's in the development branch.......

**Comment by Mathie01** [comment]
So as of 19 April, it's time to deploy the patch on master. No ?

**Comment by Scraayp** [comment]
It's kindao ur choice when we push things thnx. And no.

I'm working on an update which needs to be finished before.
