### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by pog-sister** [Michael-J-Scofield/discord-anti-spam#121]
I was scrolling through the code after I cloned it so I could see what exactly you guys did to make it because I was interested in making my own anti-spam system and I saw in    index.d.ts   there is an error line 11   RichEmbed   Module '"discord.js"' has no exported member 'RichEmbed'.   Idk if you guys wanna fix that or look into it

**Comment by Scraayp** [comment]
Thanks you for telling us! We'll check into it.
