### ISSUE TITLE
Docs not there

### ISSUE THREAD

**Issue by Kief5555** [Michael-J-Scofield/discord-anti-spam#132]
**Describe the bug**
There is no docs on the website 

**To Reproduce**
1. Go to 'The web'
2. Click on 'Here' you can find the documentation **Here**
3. See error

**Expected behavior**
Take you to the same page

**Comment by Scraayp** [comment]
Then it's your pc.
I just see the docs fine. [Link](https://discord-anti-spam.js.org/global.html)

**Comment by Kief5555** [comment]
Ah, 

Did a restart thanks!
