### ISSUE TITLE
Work with discordjs v13 ?

### ISSUE THREAD

**Issue by Cyril-Beeckman** [Michael-J-Scofield/discord-anti-spam#133]
I am searching for a antispam for my new bot.

Did this one works with discordjs v13 ?

Thanks

**Comment by Scraayp** [comment]
It's in the work.

For now I'm waiting for them to fix the most bugs.

**Comment by Kief5555** [comment]
Not working for me, terminal:
```node_modules/discord-anti-spam/index.js:497
                if (options.ignoredPermissions.some((permission) => member.hasPermission(permission))) return false
                                                                           ^

TypeError: member.hasPermission is not a function```

**Comment by TeoxModding** [comment]
@Kief5555 
https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=permissions

**Comment by Scraayp** [comment]
As I said. Discord.js v13 compability will be aviable at v2.6.0.

**Comment by kc1nn4y** [comment]
When is 2.6 being released

**Comment by Kief5555** [comment]
> @Kief5555
> https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=permissions

Yep, Ok. permissions.has in v13

**Comment by Scraayp** [comment]
Now only publish to npm! Could take up a day or 2.

**Comment by kc1nn4y** [comment]
Niceee

**Comment by Kief5555** [comment]
Lets go!
