### ISSUE TITLE
DiscordAPIError: Unknown Message

### ISSUE THREAD

**Issue by comicallybad** [Michael-J-Scofield/discord-anti-spam#140]
I tried using this package a long time ago and due to this problem I gave up on trying to use it. I saw that the issue had been "fixed," so I gave it a try again, and I still am getting this issue when there is spam. I spam, I get the warning to please stop spamming, and then crash.

throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Unknown Message
    at RequestHandler.execute (C:\Users\.....\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\.....\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async MessageManager.delete (C:\Users\.....\node_modules\discord.js\src\managers\MessageManager.js:126:5) {
  method: 'delete',
  path: '/channels/839381329891164211/messages/890143110783463445',
  code: 10008,
  httpStatus: 404
}

I have no other bots deleting messages. So I do not know what is causing it. 

![image](https://user-images.githubusercontent.com/50148901/134305759-d17d3f99-5fb7-40ab-99b4-82b4cfc6adef.png)

As you can see, spam, warning message, all messages got deleted before the warning, then app crash.

**Comment by comicallybad** [comment]
As well, I cannot seem to get any events to trigger. The warning is sent, but antiSpam.on("warnAdd"... is not triggering the event as I want to log these warnings to a channel

**Comment by Scraayp** [comment]
Which version you use?

**Comment by Scraayp** [comment]
And try doing verbose: false.

**Comment by comicallybad** [comment]
The antiSpam.message() cannot be within an async function. I think this is pretty annoying, but it is what it is, I found a way around it

**Comment by Scraayp** [comment]
Why close it than. I will fix it cmon.

**Comment by Scraayp** [comment]
Coul you please give me your code as hastebin file?

**Comment by comicallybad** [comment]
This was the original code. My hasPermissions() function commonly will not function without an await. However in this case removing the async and await caused seems to have no effect yet, it has caused me issues before. Don’t mind my useless catch statement I forgot to remove. https://paste.menudocs.org/paste/xz6xz

**Comment by Scraayp** [comment]
in your antispam options. Try doing verbose: false.

**Comment by comicallybad** [comment]
> in your antispam options. Try doing verbose: false.

I have verbose set to false. Here are my options: 
client.antiSpam = new AntiSpam({
    warnThreshold: 5, muteThreshold: 7, kickThreshold: 99, banThreshold: 99, maxInterval: 2000,
    warnMessage: '{@user}, Please stop spamming or you will be muted.',
    kickMessage: '**{user_tag}** has been kicked for spamming.',
    muteMessage: '**{user_tag}** has been muted for spamming.',
    maxDuplicatesWarning: 6, maxDuplicatesKick: 99, maxDuplicatesBan: 99, maxDuplicatesMute: 8,
    ignoredPermissions: ['MANAGE_NICKNAMES'],
    ignoreBots: true, verbose: false, muteRoleName: "Muted",
    removeMessages: true, removeBotMessages: true, removeBotMessagesAfter: 15000,
});
I don’t want to use the kick and ban feature, however I found another issue, if I don’t supply a kick or ban message then the event for mute add does not trigger

**Comment by Scraayp** [comment]
So unkown message error 

I don’t want to use the kick and ban feature, however I found another issue, if I don’t supply a kick message then the event for mute add does not trigger

**Comment by Scraayp** [comment]
Just for me, so i can see it faster on pr

**Comment by Scraayp** [comment]
And which version of the package do you use?

**Comment by comicallybad** [comment]
> And which version of the package do you use?

I’m on the version 2.5.8. I’m also on discord.js v12.5.3 so I’m not sure if that could be the issue. Updating to v12 was the most hell experience ever with them changing the message.delete() and now that they’ve changed channel.send() and many other methods, I am not trying to update anytime soon lol.

**Comment by Scraayp** [comment]
You will need. In april it will be required

**Comment by comicallybad** [comment]
> You will need. In april it will be required

That’s gonna be fun then lol rip, so many changes to common methods. I made a global delete function to make that easier. Probably will do the same for send and some other functions.

**Comment by Scraayp** [comment]
I head its already deprecated

**Comment by Scraayp** [comment]
What needs to be done:

- [ ] Unkown Message error
- [ ] I don’t want to use the kick and ban feature, however I found another issue, if I don’t supply a kick message then the event for mute add does not trigger

**Comment by Scraayp** [comment]
"  I don’t want to use the kick and ban feature, however I found another issue, if I don’t supply a kick message then the event for mute add does not trigger" 

I checked the code and this should not be the case! Please make sure nothing else is breaking it.

**Comment by Scraayp** [comment]
Also unknown message error should be fixed!
