### ISSUE TITLE
attachments and dublicates problems

### ISSUE THREAD

**Issue by ghost** [Michael-J-Scofield/discord-anti-spam#15]
after working with your code and rewriting it to my own needs, a few users and me found things that needed to be fixed. ( fixed the most for myself)
for example the attachments. If you send multiple  attachments, the script detects it as dubplicates, because msg.content is empty when you only attach a file. So you will get warned.

also is this script a nice beginning but not useful for bots that run longer than one day and dont restart. Why you may ask, because (maybe I didnt saw it in the code ) you would get warned and maybe banned when you say "Hello" multiple times splited on a few hours or maybe days. My ideas where to clear the message history every 30min or also make a interval for dublicates.
dont get me wrong, Iam just trying to give advices to make the code better

**Comment by MrAugu** [comment]
1) The message thingy: The message event is emitted by Discord itself, we can't do really anything about it.
2) Longevity: When i started working on code i saw it isn't available at-scale, planning to split them in different things, for each guild just as music bots does.

Thank for your opinion and ideas. They're appreciated.

**Comment by MrAugu** [comment]
Attachament bug has been fixed as [Pull Request #27](https://github.com/Michael-J-Scofield/discord-anti-spam/pull/27). 

Duplication bug has been added on to do list. It may even be fixed, ain't texted. 😅

**Comment by tabamodz** [comment]
mine gets an error of
PS D:\Downloads\DiscordBot> node .
D:\Downloads\DiscordBot\index.js:5
client.on('ready', () => {
^

ReferenceError: client is not defined
    at Object.<anonymous> (D:\Downloads\DiscordBot\index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
PS D:\Downloads\DiscordBot>
what is this please fix

**Comment by MrAugu** [comment]
client is what you define new Discord.Client();

**Comment by MrAugu** [comment]
This issue is now obsolete as both things have been figured out and fixed out.

**Comment by tabamodz** [comment]
Im sorry I don’t understand

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Michael-J-Scofield** [comment]
Please open a new issue if you're still experiencing issues with the new version.
