### ISSUE TITLE
Option to watch for cross-posting

### ISSUE THREAD

**Issue by NekoNyanners** [Michael-J-Scofield/discord-anti-spam#156]
A lot of Servers suffer from spammers that spam the same message **once** in many **different** channels which circumvents many spam protections. It would be nice having a feature which detects this kind of cross posting :) 
Thank you for your amazing work!

**Comment by Scraayp** [comment]
We could add that, the problem is. This package is anti spam based. What I could do is create a new option that you can turn on to enable anti spam. The only problem is, the list would need to be reviewed on every add. But I could try to figure out a way.

**Comment by Scraayp** [comment]
I have decided that I'm gonna start a new package for that. So this is not gonna be included into this package.
