### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Enderisss** [Michael-J-Scofield/discord-anti-spam#17]
Hey, i have it like this

const Discord = require("discord.js");
var anti_spam = require("discord-anti-spam");
const bot = new Discord.Client()
module.exports = {
    on: 'message', 
    code(message) {

        anti_spam(bot, {
            warnBuffer: 3, //Maximum amount of messages allowed to send in the interval time before getting warned.
            maxBuffer: 5, // Maximum amount of messages allowed to send in the interval time before getting banned.
            interval: 10000, // Amount of time in ms users can send a maximum of the maxBuffer variable before getting banned.
            warningMessage: "stop spamming or I'll whack your head off.", // Warning message send to the user indicating they are going to fast.
            banMessage: "has been banned for spamming, anyone else?", // Ban message, always tags the banned user in front of it.
            maxDuplicatesWarning: 7,// Maximum amount of duplicate messages a user can send in a timespan before getting warned
            maxDuplicatesBan: 10, // Maximum amount of duplicate messages a user can send in a timespan before getting banned
            deleteMessagesAfterBanForPastDays: 7 // Delete the spammed messages after banning for the past x days.
          });
        }
    }

Doesn't seem to do anything. Only says that messages have been logged after 11 of them were posted.

**Comment by Michael-J-Scofield** [comment]
below seems to work for me.

```js
const Discord = require("discord.js");
const client = new Discord.Client();

const antispam = require('discord-anti-spam');

antispam(client, {
  warnBuffer: 3, //Maximum amount of messages allowed to send in the interval time before getting warned.
  maxBuffer: 5, // Maximum amount of messages allowed to send in the interval time before getting banned.
  interval: 1100, // Amount of time in ms users can send a maximum of the maxBuffer variable before getting banned.
  warningMessage: "stop spamming or I'll whack your head off.", // Warning message send to the user indicating they are going to fast.
  banMessage: "has been banned for spamming, anyone else?" // Ban message, always tags the banned user in front of it.
});

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('message', msg => {
  if (msg.content === 'ping') {
    msg.reply('Pong!');
  }
});

client.login('token');
```
