### ISSUE TITLE
SyntaxError: Unexpected token ;

### ISSUE THREAD

**Issue by MLiranG** [Michael-J-Scofield/discord-anti-spam#2]
![image](https://user-images.githubusercontent.com/30736093/31484883-9c2435b4-af3a-11e7-9c3d-2667247bf19a.png)

Getting this err,
help?
P.S. I need to put that in the message event?

**Comment by Leownn** [comment]
There are many typos in the example, I am already helping you in Discord.js Official server anyway. When I have time I will open a pull request that should fix the example code

**Comment by Michael-J-Scofield** [comment]
Readme fixed. And what do you even mean with: `I am already helping you in Discord.js Official server anyway` since I'm not even in that server

**Comment by Leownn** [comment]
That was to MLiranG

**Comment by Michael-J-Scofield** [comment]
Alright, I updated the example. Haven't actually checked this package in a while so lemme know if you have issues and I might make some time and fix it.
