### ISSUE TITLE
Doesn't mention user

### ISSUE THREAD

**Issue by dusjazz** [Michael-J-Scofield/discord-anti-spam#25]
On my server it starts with the userid and not with a mention.

**Comment by dusjazz** [comment]
v12.0.0-dev at Master

**Comment by MrAugu** [comment]
Most probably because the module includes discord.js code which is incompatible with v12.0.0-dev. Probably will get fixed when the 12.0.0 is out.

**Comment by MrAugu** [comment]
Okay, my last comment was bad. Im currently working on it and i will make sure thatit will work.

**Comment by MrAugu** [comment]
Fixed as [Pull Request #27](https://github.com/Michael-J-Scofield/discord-anti-spam/pull/27).

**Comment by MrAugu** [comment]
~~This issue is fixed, issue can be closed.~~
