### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by bobroe111** [Michael-J-Scofield/discord-anti-spam#26]
Bot treats multiple users as one, if person 1 send chat, then 2, then 3. Person 3 gets a warning

**Comment by MrAugu** [comment]
This may be because the bot treats users with they'r Username#Tag instead of discord **unique** ID. Will fix it.

**Comment by MrAugu** [comment]
Just created a pull requests to fix many stuff and improve performance and scalability. I have no idea if this problem persists but it should't. Will look into this for you,

**Comment by MrAugu** [comment]
Fixed as [Pull Reques #17](https://github.com/Michael-J-Scofield/discord-anti-spam/pull/27).

**Comment by Michael-J-Scofield** [comment]
merged in aa342b77801c786886a8692509271a9892995e8a
