### ISSUE TITLE
Is it possible to parse value in a json file?

### ISSUE THREAD

**Issue by Owned67** [Michael-J-Scofield/discord-anti-spam#32]
possible to include the values in a  json file, as a sample:
{
  "warnBuffer"  : "3",
  "maxBuffer" : "5",
  "interval"  : "logs",
  "warningMessage"  : "please stop spamming!",
  "banMessage": "blablabla"
}

**Comment by MrAugu** [comment]
Yes it is. It will require you to parse the file and set values in as the way we provide.

**Comment by Owned67** [comment]
Thanks 👍
