### ISSUE TITLE
Missing of Discord Server

### ISSUE THREAD

**Issue by MrAugu** [Michael-J-Scofield/discord-anti-spam#35]
For easy support create a support server where peoples can easily discuss issues they are running into, etc.

**Comment by Michael-J-Scofield** [comment]
Who would be providing the support?

**Comment by ShayBox** [comment]
You. The creator of this package.

**Comment by xseano** [comment]
Honestly ^ lmao

**Comment by xseano** [comment]
Support would be provided by contributors, collaborators, and (obviously) the primary maintainer. Thus, creating a community for people to interact and help each other out with this library.

**Comment by MrAugu** [comment]
> Support would be provided by contributors, collaborators, and (obviously) the primary maintainer. Thus, creating a community for people to interact and help each other out with this library.

Best reply outta here.


> Who would be providing the support?
I can help. 😅

**Comment by Michael-J-Scofield** [comment]
Thanks for the input @xseano and @mrAugu 
I'm going to boot up a Discord server over the weekend. But I will keep actual issues on here and it will probably only be for support and suggestions.

**Comment by MrAugu** [comment]
If you need i could do it and transfer ownership to you when you enter.

**Comment by Michael-J-Scofield** [comment]
still need to set stuff up but you guys can join here [https://discord.gg/sDRvcyR](https://discord.gg/sDRvcyR)
