### ISSUE TITLE
Bot responds to other bots.

### ISSUE THREAD

**Issue by olvrb** [Michael-J-Scofield/discord-anti-spam#4]
add a message.author.bot to all warning things

**Comment by olvrb** [comment]
also, adding an option to ignore a certain role or user ID would be great

**Comment by Snarr** [comment]
Just add the line "if (msg.author.bot) return" to your code so that nothing happens if the author is a bot.

**Comment by Michael-J-Scofield** [comment]
Feel free to fork

**Comment by Kolkies** [comment]
See [https://github.com/Michael-J-Scofield/discord-anti-spam/pull/9](#9 )

**Comment by Kolkies** [comment]
@Michael-J-Scofield

**Comment by Michael-J-Scofield** [comment]
Merged
