### ISSUE TITLE
Is it possible to run code when a user hits the buffer?

### ISSUE THREAD

**Issue by JaxTheWolf** [Michael-J-Scofield/discord-anti-spam#5]
Hello, I have a little question. Is it possoble to execute code when someone hits the buffer? If so, how?
Any help is appreciated.

-JaxTheWolf

**Comment by Snarr** [comment]
You could simply insert the code into the warn() or ban() methods, depending on when you want it to run.

**Comment by JaxTheWolf** [comment]
Awesome! Thank you!
