### ISSUE TITLE
Duplicates warnings dont work

### ISSUE THREAD

**Issue by mage-ua** [Michael-J-Scofield/discord-anti-spam#51]
Here is a mistake in messageCache array. It must be **messageCache.content** instead of **messageCache.message**,
In **messageMatches** we are checking property **content**.

`messageCache.push({
			"message": message.content,
			"author": message.author.id
		});`
`let messageMatches = messageCache.filter((m) => m.content === message.content && m.author === message.author.id).length;`

**Comment by Michael-J-Scofield** [comment]
Fixed
