### ISSUE TITLE
Bot does not delete messages after ban

### ISSUE THREAD

**Issue by catsn3k** [Michael-J-Scofield/discord-anti-spam#6]
When a user is caught spamming and is banned from the bot, the bot doesn't have anything in the reason for the ban.  But most importantly, the bot doesn't delete the spammed messages, the messages should be deleted automatically if a user is banned but I'm not too sure if the bot is choosing not to delete the messages or what.

**Comment by motasim1** [comment]
Hey there,

If you look at the docs, you can see that GuildMember#Ban can take an int between 1 and 7 which is there to delete the past messages in the providen days. So say for example you put 5 in then the bot will delete the messages from the user in the past 5 days. So a fix for this one could be done easily:
Look up for the code where the bot bans the user, and place 1 or 2 like this: ban(1)

**Comment by Michael-J-Scofield** [comment]
added in latest release.
https://github.com/Michael-J-Scofield/discord-anti-spam/commit/ba274188bcee606798579e17e8573224df2f19d2
