### ISSUE TITLE
error banEnabled & kickEnabled

### ISSUE THREAD

**Issue by l2egister** [Michael-J-Scofield/discord-anti-spam#61]
ERROR
`const AntiSpam = new DiscordAntiSpam({
	kickEnabled: true,
	banEnabled: true,
	warnThreshold: 3,
	banThreshold: 5,
	kickThreshold: 30,
	maxInterval: 2000,
	warnMessage: "WARN",
	banMessage: "BAN",
	maxDuplicatesWarning: 7,
	maxDuplicatesBan: 13,
	maxDuplicatesKick: 30,
	deleteMessagesAfterBanForPastDays: 7,
	exemptPermissions: ["MANAGE_MESSAGES", "ADMINISTRATOR", "MANAGE_GUILD", "BAN_MEMBERS"],
	ignoreBots: true,
	verbose: false
});
 
AntiSpam.on("warnEmit", (member) => console.log(`Attempt to warn ${member.user.tag}.`));
AntiSpam.on("warnAdd", (member) => console.log(`${member.user.tag} has been warned.`));
AntiSpam.on("kickEmit", (member) => console.log(`Attempt to kick ${member.user.tag}.`));
AntiSpam.on("kickAdd", (member) => console.log(`${member.user.tag} has been kicked.`));
AntiSpam.on("banEmit", (member) => console.log(`Attempt to ban ${member.user.tag}.`));
AntiSpam.on("banAdd", (member) => console.log(`${member.user.tag} has been banned.`));
AntiSpam.on("dataReset", () => console.log("Module cache has been cleared."));
client.on("message", (msg) => {
	AntiSpam.message(msg);
});`

`2019-10-27T11:30:36.920122+00:00 app[worker.1]:/app/node_modules/discord-anti-spam/index.js:74
2019-10-27T11:30:36.920140+00:00 app[worker.1]:       if (!banEnabled) return;
2019-10-27T11:30:36.920143+00:00 app[worker.1]:       ^
2019-10-27T11:30:36.920145+00:00 app[worker.1]: 
2019-10-27T11:30:36.920147+00:00 app[worker.1]: ReferenceError: banEnabled is not defined`

**Comment by Sanchezo** [comment]
I have same issue

**Comment by wvssxm** [comment]
same issue

**Comment by Androz2091** [comment]
Closed in #64
