### ISSUE TITLE
SyntaxError: Invalid shorthand property initialize

### ISSUE THREAD

**Issue by ShotDev** [Michael-J-Scofield/discord-anti-spam#7]
![image](https://user-images.githubusercontent.com/34286241/34052604-593e057a-e1c3-11e7-99a7-ed5f2400b71c.png)

**Comment by Dreamyplayer** [comment]
Same Error Help Please

**Comment by RedJambo123** [comment]
For those having issues you need to replace the equals (=) sign with a colon (:).

So:

```javascript
maxDuplicatesWarning = 7
maxDuplicatesBan = 10
```

should become:

```javascript
maxDuplicatesWarning: 7,
maxDuplicatesBan: 10
```
