### ISSUE TITLE
Code Doesn't Work

### ISSUE THREAD

**Issue by VeryAvaila** [Michael-J-Scofield/discord-anti-spam#71]
So, I had a bot already made and thought it will be nice to have an anti-spam feature on it. Since I was new I used the example code. I changed the values of the code to what I wanted, then I tried it out with my friend. It didn't work for some reason and didn't give any error in the console. Please respond soon, Thanks.

**Comment by Edude42** [comment]
Can you post the code you're using right now?

**Comment by Androz2091** [comment]
Closed due to inactivity.
