### ISSUE TITLE
Duplicate Messages Issue

### ISSUE THREAD

**Issue by DangoTV** [Michael-J-Scofield/discord-anti-spam#72]
Greetings,

I've noticed that you have a "maxInterval" value which represents the amount of time in which messages are considered spam. However, there is no variable to evaluate the same thing but for duplicate messages. Which means that currently, when you've got something like this:

maxDuplicatesWarning: 5
maxDuplicatesKick: 10

Users will get kicked on the 10th duplicate message they send, even if it's over a day of messages in total. Which makes no sense at all, please add a "maxDuplicatesInterval" to serve the same function but for duplicate messages.

I've already tried fixing it myself by setting a timer to reset the cache at every 1 minute or so but just recently, the servers which host the bot had some downtime and it caused the bot to go on a kill spree basically and kick people because the cache wasn't getting reset.

**Comment by Androz2091** [comment]
Added
