### ISSUE TITLE
Add `ignoreOwner` options

### ISSUE THREAD

**Issue by Androz2091** [Michael-J-Scofield/discord-anti-spam#77]
Add an `ignoreOwner` option:
```js
new antiSpam({
    ignoreOwner: true // Whether to ignore messages from the server owner
});
```
Actually, it's like `true` by default

**Comment by NotSugden** [comment]
i think it should just always ignore the owner, no matter what, because it will throw errors trying to ban or kick the owner, and you cant stop the owner from spamming no matter what you do

**Comment by Edude42** [comment]
Maybe also an option to ignore roles the bot can't kick/ban?

**Comment by NotSugden** [comment]
> Maybe also an option/feature to ignore roles and members the bot can't kick/ban? That would solve the ignoreOwner addition and more.

you can already do this using the `ignoredRoles` option

**Comment by Edude42** [comment]
> you can already do this using the ignoredRoles option
`ignoredRoles` works with an array of ids though. What about public bots? The owner of the bot can't ask every server what roles the bot can't access.

**Comment by NotSugden** [comment]
> > you can already do this using the ignoredRoles option
> 
> `ignoredRoles` works with an array of ids though. What about public bots? The owner of the bot can't ask every server what roles the bot can't access.

you can actually use a function for `ignoredRoles`, which has the Role as the parameter, and returns a boolean indicating if it should be ignored or not

**Comment by Androz2091** [comment]
It could have been useful for testing, currently people are forced to use a second account. Each time I want to add a feature I have to modify the lib to disable the owner condition.

**Comment by NotSugden** [comment]
> It could have been useful for testing, currently people are forced to use a second account. Each time I want to add a feature I have to modify the lib to disable the owner condition.

maybe add a `testMode` option instead for this use case?

**Comment by Androz2091** [comment]
Yes, good idea

**Comment by Androz2091** [comment]
I added a `debug` mode.
