### ISSUE TITLE
Can you get the bot to remove spammed messages

### ISSUE THREAD

**Issue by EddiesTech** [Michael-J-Scofield/discord-anti-spam#80]
If someone is caught spamming, it tells them to stop but doesn't delete the messages. It leaves them there. I want the spam messages to be deleted, even if the person isn't banned

**Comment by spud-69** [comment]
try using something like `msg.delete(author.msg)` or something along those lines. or you can make a `Prune` and then tag the user and the amount of messages.

**Comment by Scraayp** [comment]
I am working on this suggestion. 
This will be implemented in the next update

**Comment by EddiesTech** [comment]
Great! Can't wait! :)

**Comment by Scraayp** [comment]
@EddiesTech it is inplemented in the #94 .

**Comment by Scraayp** [comment]
This will be added in the next update
