### ISSUE TITLE
all event's except warnAdd are returning null for the member and reaction messages cannot be added as spam.

### ISSUE THREAD

**Issue by comicallybad** [Michael-J-Scofield/discord-anti-spam#87]
I am on Discord.js v12, not sure if that is the issue, as the package doesn't say anything about the Discord.js version. As well, I was hoping to mark reaction spamming as a form of spam, but on client.on('messageReactionAdd', =>(messageReaction, user)), I send antiSpam.message(messageReaction.message) and there is no luck. I do the same for messageReactionRemove, so it shouldn't be a time issue. As well, messageReaction.message is a regular message object return, just like client.on('message', (message)) object when compared in console log. The bot is still warning, kicking, and banning users upon spam, not sure why the event's are returning null if the events are actually working.

**Comment by Androz2091** [comment]
I will look into it as soon as possible, I'll keep you informed.

**Comment by Scraayp** [comment]
This should be fixed in the next update
