### ISSUE TITLE
Mutes not working at all

### ISSUE THREAD

**Issue by cayoten** [Michael-J-Scofield/discord-anti-spam#96]
On the mute event, it just completely forgets to mute and skips over it. (with MuteEnabled: true,)

_const AntiSpam = require('discord-anti-spam');
const antiSpam = new AntiSpam({
    warnThreshold: 4,
    kickThreshold: 8,
    banThreshold: 12,
    muteThreshold: 6,
    maxInterval: 5000,
    maxDuplicatesInterval: 5000,
    muteRoleName: "Muzzled",
    warnMessage: '{@user}, Please stop spamming.',
    muteMessage: '**{user_tag}** has been muted for spamming.',
    kickMessage: '**{user_tag}** has been kicked for spamming.',
    banMessage: '**{user_tag}** has been banned for spamming.',
    errorMessages: true,
    kickErrorMessage: "Could not kick **{user_tag}** because of improper permissions.",
    banErrorMessage: "Could not ban **{user_tag}** because of improper permissions.",
    muteErrorMessage: "Could not mute **{user_tag}** because of improper permissions or the mute role couldn't be found.",
    maxDuplicatesWarning: 7,
    maxDuplicatesKick: 10,
    maxDuplicatesBan: 10,
    maxDuplicatesMute: 9,
    exemptPermissions: ["MANAGE_MESSAGES"],
    ignoreBots: true,
    warnEnabled: true,
    kickEnabled: false,
    muteEnabled: true,
    banEnabled: false
});_

**Comment by Androz2091** [comment]
Yes, as you can see it's currently on the develop branch. The @Scraayp's PR wasn't entirely complete. Anyway, thank you for your report, it will be fixed.

**Comment by Scraayp** [comment]
Yeah i am working testing ect..
Use for now the master brench instead

**Comment by Scraayp** [comment]
This will be fixed in the next update

**Comment by TitanskullhunterYT** [comment]
did this issue get updated yet or am I just dumb and I am just having problems with this command

**Comment by Scraayp** [comment]
Mute hasn't been uploaded to npm yet

**Comment by Scraayp** [comment]
So it's prob not gonna work
